#+TITLE: Distribution of points on the surface of the sphere
#+SUBTITLE: A self-study case to code develoment, documantation and Git.
#+AUTHOR: Baudilio Tejerina

* Introduction

  This project is merely intended to learn and practice software development techniques using Git
  version control and Github services.

  The project consists in the classic distribution of points on the surface of a sphere. References will be provided.

  I will use Fortran 90 as programming language with the editor Emacs.

  Small modification with this line done in TY. (testing only).

* Emacs

** The directory local variables


* Directory structure of the project

 The CWD, which is a git repositor, and two subdirectories: prog/ and lib/
 In addition CWD contains .git/, .dir-locals.el, .gitignore, README.org (this file), README.md

 For CMake, I've added the file [[file:CMakeLists.txt][CMakeLists.txt]]

 prog/ contains the source code, main.f90 and another [[file:prog/CMakeLists.txt][file:~/spheres/prog/CMakeLists.txt]]
 lib/ contains its own [[file:lib/CMakeLists.txt][CMakeLists.txt]] and code that constitute the library of the project.

* CMake

  With this structure


* Download

* Use

* Reference
